-- CSMJU-BFTS initial schema
-- Generated by hand from prisma/schema.prisma (see file for design rationale
-- and explicit ASSUMPTION notes on unresolved business rules).

CREATE TYPE "Role" AS ENUM ('STUDENT', 'TREASURER', 'BRANCH_HEAD');
CREATE TYPE "TransactionType" AS ENUM ('INCOME', 'EXPENSE', 'ADJUSTMENT');
CREATE TYPE "TransactionStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'VOIDED', 'NEEDS_REVIEW');
CREATE TYPE "TransactionSourceType" AS ENUM ('MANUAL', 'BANK_IMPORT', 'ADJUSTMENT');
CREATE TYPE "ApprovalDecision" AS ENUM ('APPROVE', 'REJECT', 'VOID');
CREATE TYPE "IntegrationEventStatus" AS ENUM ('RECEIVED', 'PARSED', 'VALIDATED', 'DUPLICATE', 'NEEDS_REVIEW', 'ERROR', 'PROCESSED');

CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "external_user_id" TEXT NOT NULL,
    "display_name" TEXT NOT NULL,
    "student_code" TEXT,
    "role" "Role" NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "users_external_user_id_key" ON "users"("external_user_id");

CREATE TABLE "year_accounts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "year_level" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "academic_year_label" TEXT,
    "opening_balance" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "currency" TEXT NOT NULL DEFAULT 'THB',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "year_accounts_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "year_accounts_year_level_key" ON "year_accounts"("year_level");

CREATE TABLE "user_year_assignments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "year_account_id" UUID NOT NULL,
    "role" "Role" NOT NULL,
    "active_from" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "active_to" TIMESTAMPTZ,
    CONSTRAINT "user_year_assignments_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "user_year_assignments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id"),
    CONSTRAINT "user_year_assignments_year_account_id_fkey" FOREIGN KEY ("year_account_id") REFERENCES "year_accounts"("id")
);
CREATE INDEX "user_year_assignments_year_account_id_role_idx" ON "user_year_assignments"("year_account_id", "role");

-- SELF-REVIEW FIX: DB-level guarantee that at most one *active* TREASURER
-- assignment exists per year account at a time (Prisma schema syntax
-- cannot express a partial unique index, so this is raw SQL only — it is
-- NOT reflected in prisma/schema.prisma and Prisma will therefore not know
-- about it; do not let `prisma migrate reset` regenerate this file from the
-- schema without re-adding this line, or the guarantee is silently lost).
CREATE UNIQUE INDEX "uq_active_treasurer_per_year"
  ON "user_year_assignments" ("year_account_id")
  WHERE "role" = 'TREASURER' AND "active_to" IS NULL;

CREATE TABLE "transactions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "year_account_id" UUID NOT NULL,
    "type" "TransactionType" NOT NULL,
    "status" "TransactionStatus" NOT NULL DEFAULT 'PENDING',
    "amount" DECIMAL(14,2) NOT NULL CHECK ("amount" > 0),
    "transaction_date" DATE NOT NULL,
    "description" TEXT NOT NULL,
    "category" TEXT,
    "source_type" "TransactionSourceType" NOT NULL,
    "external_reference" TEXT,
    "idempotency_key" TEXT,
    "created_by" UUID NOT NULL,
    "approved_by" UUID,
    "approved_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "transactions_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "transactions_year_account_id_fkey" FOREIGN KEY ("year_account_id") REFERENCES "year_accounts"("id"),
    CONSTRAINT "transactions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id"),
    CONSTRAINT "transactions_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "users"("id")
);
CREATE UNIQUE INDEX "transactions_idempotency_key_key" ON "transactions"("idempotency_key");
CREATE INDEX "transactions_year_account_id_transaction_date_idx" ON "transactions"("year_account_id", "transaction_date");
CREATE INDEX "transactions_year_account_id_status_idx" ON "transactions"("year_account_id", "status");
CREATE INDEX "transactions_external_reference_idx" ON "transactions"("external_reference");
CREATE INDEX "transactions_created_by_idx" ON "transactions"("created_by");

CREATE TABLE "expense_evidence" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "transaction_id" UUID NOT NULL,
    "storage_key" TEXT NOT NULL,
    "original_filename" TEXT NOT NULL,
    "mime_type" TEXT NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "checksum" TEXT,
    "uploaded_by" UUID NOT NULL,
    "uploaded_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "version" INTEGER NOT NULL DEFAULT 1,
    "is_current" BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT "expense_evidence_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "expense_evidence_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id"),
    CONSTRAINT "expense_evidence_uploaded_by_fkey" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id")
);
CREATE INDEX "expense_evidence_transaction_id_is_current_idx" ON "expense_evidence"("transaction_id", "is_current");

CREATE TABLE "approval_actions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "transaction_id" UUID NOT NULL,
    "actor_id" UUID NOT NULL,
    "decision" "ApprovalDecision" NOT NULL,
    "reason" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "approval_actions_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "approval_actions_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id"),
    CONSTRAINT "approval_actions_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id")
);
CREATE INDEX "approval_actions_transaction_id_idx" ON "approval_actions"("transaction_id");

CREATE TABLE "integration_sources" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "year_account_id" UUID NOT NULL,
    "provider" TEXT NOT NULL,
    "channel" TEXT,
    "external_source_id" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "configuration_ref" TEXT,
    CONSTRAINT "integration_sources_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "integration_sources_year_account_id_fkey" FOREIGN KEY ("year_account_id") REFERENCES "year_accounts"("id")
);

CREATE TABLE "integration_events" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "integration_source_id" UUID NOT NULL,
    "external_event_id" TEXT NOT NULL,
    "received_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "raw_payload_ref" TEXT,
    "parsed_status" "IntegrationEventStatus" NOT NULL DEFAULT 'RECEIVED',
    "error_code" TEXT,
    "processing_attempts" INTEGER NOT NULL DEFAULT 0,
    "processed_transaction_id" UUID,
    CONSTRAINT "integration_events_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "integration_events_integration_source_id_fkey" FOREIGN KEY ("integration_source_id") REFERENCES "integration_sources"("id"),
    CONSTRAINT "integration_events_processed_transaction_id_fkey" FOREIGN KEY ("processed_transaction_id") REFERENCES "transactions"("id")
);
CREATE UNIQUE INDEX "integration_events_source_external_event_key" ON "integration_events"("integration_source_id", "external_event_id");

CREATE TABLE "audit_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "actor_id" UUID,
    "action" TEXT NOT NULL,
    "target_type" TEXT NOT NULL,
    "target_id" UUID NOT NULL,
    "year_account_id" UUID,
    "before_json" JSONB,
    "after_json" JSONB,
    "metadata_json" JSONB,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "audit_logs_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id"),
    CONSTRAINT "audit_logs_year_account_id_fkey" FOREIGN KEY ("year_account_id") REFERENCES "year_accounts"("id")
);
CREATE INDEX "audit_logs_target_type_target_id_created_at_idx" ON "audit_logs"("target_type", "target_id", "created_at");

-- Append-only enforcement for audit_logs (Security Model #6). Run as a
-- privileged migration step once the application's runtime DB role is known:
--   REVOKE UPDATE, DELETE ON "audit_logs" FROM app_runtime_role;
--   GRANT INSERT, SELECT ON "audit_logs" TO app_runtime_role;
